---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  tasks:
    - name: "create .bash_profile"
      file:
        path: ~/.bash_profile
        state: touch

    - name: set environment variables
      blockinfile:
        path: ~/.bash_profile
        block: |
          export ENVIRONMENT="production"
          export NODE_ENV="production" 
          export VERSION=1
          export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST')}}"
          export TYPEORM_PORT="{{ lookup('env', 'TYPEORM_PORT')}}" 
          export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION')}}"
          export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES')}}"
          export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME')}}"
          export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD')}}"
          export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE')}}"
          export TYPEORM_MIGRATIONS="{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
          export TYPEORM_MIGRATIONS_DIR="{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

  roles:
    - configure-server
