---
- name: Install nvm
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash"
  args:
    creates: "~/.nvm/nvm.sh"

- name: Install node and set version
  become: true
  become_user: root
  shell: "source ~/.nvm/nvm.sh && nvm install 13.6.0 && nvm alias default 13.6.0"
  args:
    executable: /bin/bash
    creates: "~/.nvm/alias"

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
