---
- name: Install nvm
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash"
  args:
    warn: false

- name: Add command to load nvm in .bashrc
  shell: echo "[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh" >> ~/.bashrc

- name: Install node and set version
  shell: "source .nvm/nvm.sh && nvm install 13.8.0 && nvm alias default 13.8.0"
  args:
    executable: /bin/bash

- name: "Install pm2"
  shell: "source .nvm/nvm.sh && nvm use default && npm install -g pm2"
  args:
    executable: /bin/bash
