---
- name: "create backend-app dir."
  file:
    path: ~/backend-app
    state: directory

- name: "cp backend from project to backend-app."
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: ~/backend-app

- name: "run backend using pm2."
  shell: |
    cd ~/backend-app
    npm install 
    pm2 stop default
    pm2 start npm -- start
