---
- name: "create backend-app dir."
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "run backend using pm2."
  shell: |
    source ~/.nvm/nvm.sh
    npm install
  args:
    chdir: ~/backend-app
    executable: /bin/bash

- name: "run backend using pm2."
  shell: |
    source ~/.nvm/nvm.sh
    pm2 start main.js
  args:
    chdir: ~/backend-app/dist
    executable: /bin/bash
