---
- name: "create backend-app dir."
  file:
    path: ~/backend-app
    state: directory

- name: "cp backend artifact from project to backend-app."
  copy:
    src: /root/project/artifact.tar.gz
    dest: /tmp/artifact.tar.gz

- name: "install gzip and tar"
  become: true
  apt:
    name: ["gzip", "tar"]
    state: present

- name: "cp backend artifact from project to backend-app."
  shell: tar -xzvf /tmp/artifact.tar.gz -C ~/backend-app

- name: "export Environment variables"
  shell: |
    export TYPEORM_CONNECTION
    export VERSION=1
    export NODE_ENV=production
    export ENVIRONMENT=production
    export TYPEORM_MIGRATIONS_DIR=./src/migrations
    export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
    export TYPEORM_MIGRATIONS=./src/migrations/*.ts
    export TYPEORM_HOST=udapeople-db.c0d9dxku5cy6.us-east-1.rds.amazonaws.com
    export TYPEORM_PORT=5532
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=postgres
    export TYPEORM_DATABASE=postgres

- name: "run backend using pm2."
  become: true
  shell: |
    cd ~/backend-app
    npm install 
    pm2 stop default
    pm2 start npm -- start
